# Generated by Django 6.0.3 on 2026-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinarian',
            old_name='specialization',
            new_name='position',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='specialty',
            field=models.CharField(default='0000000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='vet_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
