# Generated by Django 6.0.3 on 2026-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rename_specialization_veterinarian_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reason',
            new_name='note',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
