# Generated by Django 6.0.3 on 2026-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_date_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(default='2024-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
    ]
