# Generated by Django 6.0.3 on 2026-03-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_medicalrecord_date_medicalrecord_record_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(default='ยา', max_length=50),
            preserve_default=False,
        ),
    ]
