# Generated by Django 6.0.3 on 2026-03-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_medicine_med_id_medicine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicine')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.medicalrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
